### ISSUE TITLE
Implementation Next Steps

### ISSUE THREAD

**Issue by lukedoolittle** [Maluuba/qgen-workshop#8]
The notebook does a great job of enumerating all of the components important to QA generation but its not totally clear (or totally clear to me at least) what the next steps would be within this implementation to make a "functional" solution. For example based on the Joint Model for Question Answering and Question Generation paper we would probably need an attention mechanism, beam search, multiple encoder/decoder layers, etc. Maybe we could make a list?

**Comment by tavianator** [comment]
The purpose of this repo is really to accompany a presentation we gave about the fundamentals of deep learning based NLP.  It's not really designed to be the starting point for a production implementation.  Then again, it's not that big so there's probably no harm in starting from it either.  I'd say in addition to your list, a very important piece from that paper that's missing here is the pointer network that generates question words by pointing inside the document, instead of being limited to the vocabulary.
